apiVersion: apps/v1
kind: Deployment
metadata:
  name: local-registry
spec:
  replicas: 1
  selector:
    matchLabels:
      app: local-registry
  template:
    metadata:
      labels:
        app: local-registry
    spec:
      containers:
      - name: registry
        image: registry:2
        ports:
        - containerPort: 5000
      # UNCOMMENT TO USE NFS FOR REGISTRY STORAGE
      #   volumeMounts:
      #   - name: registry-storage
      #     mountPath: /var/lib/registry
      # volumes:
      # - name: registry-storage
      #   persistentVolumeClaim:
      #     claimName: nfs-pvc
