apiVersion: v1
kind: Service
metadata:
  name: local-registry-service
spec:
  type: NodePort
  selector:
    app: local-registry
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 30500  # Pick a port between 30000-32767

