apiVersion: v1
kind: Service
metadata:
  name: rpi-flask-test-svc
spec:
  type: NodePort
  selector:
    app: rpi-flask-test
  ports:
  - protocol: TCP
    port: 5000        # cluster-internal port
    targetPort: 5000  # pod port
    nodePort: 30501   # pick 30000-32767

